spring:
  application:
    name: mscartoes

server:
  port: 0

eureka:
  client:
    service-url:
      default-zone: https://localhost:8761/eureka

  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
